- hosts: localhost
  tasks:
    - name: update security group tcp rule
      openstack.cloud.security_group_rule:
        security_group: default
        protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
    - name: update security group udp rule
      openstack.cloud.security_group_rule:
        security_group: default
        protocol: udp
        remote_ip_prefix: 0.0.0.0/0
    - name: update security group icmp rule
      openstack.cloud.security_group_rule:
        security_group: default
        protocol: icmp
        remote_ip_prefix: 0.0.0.0/0
    - name: create tonga network
      openstack.cloud.network:
        state: present
        name: tonga_net
        external: false
        port_security_enabled: false
    - name: create guest subnet
      openstack.cloud.subnet:
        state: present
        network_name: tonga_net
        name: guest_net
        cidr: 192.168.0.0/24
        gateway_ip: 192.168.0.1
        dns_nameservers:
           - 8.8.8.7
           - 8.8.8.8
      register: guest_subnet_output
    - name: create workstation subnet
      openstack.cloud.subnet:
        state: present
        network_name: tonga_net
        name: workstation_net
        cidr: 192.168.1.0/24
        gateway_ip: 192.168.1.1
        dns_nameservers:
           - 8.8.8.7
           - 8.8.8.8
      register: workstation_subnet_output
    - name: create office subnet
      openstack.cloud.subnet:
        state: present
        network_name: tonga_net
        name: office_net
        cidr: 192.168.2.0/24
        gateway_ip: 192.168.2.1
        dns_nameservers:
           - 8.8.8.7
           - 8.8.8.8
      register: office_subnet_output
    - name: create port with fixed ip on guest
      openstack.cloud.port:
        state: present
        name: guest1
        network: tonga_net
        fixed_ips: 
          - subnet_id: "{{ guest_subnet_output.id }}"
    - name: create port with fixed ip on workstation
      openstack.cloud.port:
        state: present
        name: workstation1
        network: tonga_net
        fixed_ips: 
          - subnet_id: "{{ workstation_subnet_output.id }}"
    - name: create port with fixed ip on office
      openstack.cloud.port:
        state: present
        name: office1
        network: tonga_net
        fixed_ips: 
          - subnet_id: "{{ office_subnet_output.id }}"
    - name: Create one guest host
      openstack.cloud.server:
        state: present
        name: guest_laptop
        image: 68a4ff73-fa5f-4e35-8abf-5f4b459b0f2c
        flavor: large
        nics: 
          - port-name: guest1
        auto_ip: false
        wait: true
        userdata: |
          {%- raw -%}#!/bin/bash
          apt update;
          apt full-upgrade -y;
          apt install -y git-all ansible;
          git clone https://github.com/kdn5436/CMMC-Compliance-Project.git;
          ansible-playbook -c local -i 127.0.0.1, -l 127.0.0.1 CMMC-Compliance-Project/src/stiglevel2/ubuntu2004-stig.yml;
          apt remove -y git-all ansible;{% endraw %}
    - name: Create one workstation host
      openstack.cloud.server:
        state: present
        name: workstation_machine1
        image: 68a4ff73-fa5f-4e35-8abf-5f4b459b0f2c
        flavor: large
        nics: 
          - port-name: workstation1
        auto_ip: false
        wait: true
        userdata: |
          {%- raw -%}#!/bin/bash
          apt update;
          apt full-upgrade -y;
          apt install -y git-all ansible;
          git clone https://github.com/kdn5436/CMMC-Compliance-Project.git;
          ansible-playbook -c local -i 127.0.0.1, -l 127.0.0.1 CMMC-Compliance-Project/src/stiglevel2/ubuntu2004-stig.yml;
          rm -rf CMMC-Compliance-Project;
          apt remove -y git-all ansible;{% endraw %}
    - name: Create an office host
      openstack.cloud.server:
        state: present
        name: jim_desktop
        image: 68a4ff73-fa5f-4e35-8abf-5f4b459b0f2c
        flavor: large
        nics: 
          - port-name: office1
        auto_ip: false
        wait: true
        userdata: |
          {%- raw -%}#!/bin/bash
          apt update;
          apt full-upgrade -y;
          apt install -y git-all ansible;
          git clone https://github.com/kdn5436/CMMC-Compliance-Project.git;
          ansible-playbook -c local -i 127.0.0.1, -l 127.0.0.1 CMMC-Compliance-Project/src/stiglevel2/ubuntu2004-stig.yml;
          rm -rf CMMC-Compliance-Project;
          apt remove -y git-all ansible;{% endraw %}
    - name: Create a router connecting the networks
      openstack.cloud.router:
        state: present
        name: router2
        network: MAIN-NAT
        interfaces:
          - net: tonga_net
            subnet: office_net
          - net: tonga_net
            subnet: workstation_net
          - net: tonga_net
            subnet: guest_net

